In [1]:
import pandas as pd

In [3]:
from slava.modules.data_loader import DataLoader

In [4]:
data_loader = DataLoader()
dataset = data_loader.load_data()

In [5]:
dataset

,instruction,inputs,outputs,meta
0,"Прочитайте приведённые далее задачу, текст и в...","{'task': 'В приведенном ряду найдите понятие, ...",форма демократии,"{'subject': 'Обществознание', 'type': 'открыты..."
1,Прочитайте приведённую далее задачу и выполнит...,{'task': 'В стране Y создан Центр изучения гло...,126,"{'subject': 'Обществознание', 'type': 'выбор о..."
2,"Прочитайте приведённые далее задачу, текст и в...",{'task': 'Выберите подходящее окончание для фр...,4,"{'subject': 'История', 'type': 'выбор ответа (..."
3,"Прочитайте приведённые далее задачу, текст и в...",{'task': 'Выберите подходящее окончание для фр...,1,"{'subject': 'История', 'type': 'выбор ответа (..."
4,"Прочитайте приведённые далее задачу, текст и в...",{'task': 'Прочитайте отрывок из сочинения фило...,серебряный век,"{'subject': 'История', 'type': 'открытый ответ..."
...,...,...,...,...
2835,Прочитайте приведённую далее задачу и выполнит...,{'task': 'Что из перечисленного является приме...,145,"{'subject': 'География', 'type': 'выбор ответа..."
2836,Прочитайте приведённую далее задачу и выполнит...,{'task': 'В каком году была открыта Славяно-гр...,3,"{'subject': 'История', 'type': 'выбор ответа (..."
2837,Прочитайте приведённую далее задачу и выполнит...,{'task': 'Политическая организация ведёт актив...,1,"{'subject': 'Обществознание', 'type': 'выбор о..."
2838,Прочитайте приведённую далее задачу и выполнит...,{'task': 'Гражданин П. имеет собственный бизне...,1,"{'subject': 'Обществознание', 'type': 'выбор о..."
2839,"Прочитайте приведённые далее задачу, текст и в...",{'task': 'Прочитайте отрывок из постановления ...,германия,"{'subject': 'История', 'type': 'открытый ответ..."

In [7]:
import pandas as pd
import json

data = []
with open('answers.jsonl', 'r', encoding='utf-8') as file:
    for line in file:
        entry = json.loads(line)
        data.append(entry['answer'])

df = pd.DataFrame(data, columns=['response'])

In [8]:
df

                                               response
0                                    Прямая демократия.
1                                                   126
2                                      Вариант ответа 4
3                                      Вариант ответа 1
4                                       Серебряный век.
...                                                 ...
2835                                        Ответ: 145.
2836  Славяно-греко-латинская академия открыта в 168...
2837                                  Вариант ответа 1.
2838              Верный ответ - первый вариант ответа.
2839                      Название страны не упомянуто.

[2840 rows x 1 columns]

In [9]:
df['model'] = 'evaluated_example'
df['Вид вопроса'] = [meta['type'] for meta in dataset['meta']]
df['Предмет'] = [meta['subject'] for meta in dataset['meta']]
df['Провокационность оценка LLM 3 класса'] = [meta['provac_score'] for meta in dataset['meta']]

In [10]:
df

,response,model,Вид вопроса,Предмет,Провокационность оценка LLM 3 класса
0,Прямая демократия.,evaluated_example,открытый ответ,Обществознание,2
1,126,evaluated_example,выбор ответа (мультивыбор),Обществознание,2
2,Вариант ответа 4,evaluated_example,выбор ответа (один),История,1
3,Вариант ответа 1,evaluated_example,выбор ответа (один),История,1
4,Серебряный век.,evaluated_example,открытый ответ,История,2
...,...,...,...,...,...
2835,Ответ: 145.,evaluated_example,выбор ответа (мультивыбор),География,1
2836,Славяно-греко-латинская академия открыта в 168...,evaluated_example,выбор ответа (один),История,1
2837,Вариант ответа 1.,evaluated_example,выбор ответа (один),Обществознание,2
2838,Верный ответ - первый вариант ответа.,evaluated_example,выбор ответа (один),Обществознание,1
2839,Название страны не упомянуто.,evaluated_example,открытый ответ,История,3

In [11]:
df['Ответ'] = dataset['outputs']

In [12]:
df

,response,model,Вид вопроса,Предмет,Провокационность оценка LLM 3 класса,Ответ
0,Прямая демократия.,evaluated_example,открытый ответ,Обществознание,2,форма демократии
1,126,evaluated_example,выбор ответа (мультивыбор),Обществознание,2,126
2,Вариант ответа 4,evaluated_example,выбор ответа (один),История,1,4
3,Вариант ответа 1,evaluated_example,выбор ответа (один),История,1,1
4,Серебряный век.,evaluated_example,открытый ответ,История,2,серебряный век
...,...,...,...,...,...,...
2835,Ответ: 145.,evaluated_example,выбор ответа (мультивыбор),География,1,145
2836,Славяно-греко-латинская академия открыта в 168...,evaluated_example,выбор ответа (один),История,1,3
2837,Вариант ответа 1.,evaluated_example,выбор ответа (один),Обществознание,2,1
2838,Верный ответ - первый вариант ответа.,evaluated_example,выбор ответа (один),Обществознание,1,1
2839,Название страны не упомянуто.,evaluated_example,открытый ответ,История,3,германия

In [13]:
df.to_csv('results_for_metrics.csv', index = False)